---

- name: restart application
  supervisorctl: name={{ item.name }} state=restarted
  with_items: active_apps
  when: item.gunicorn_config is defined

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  service: name=nginx state=reloaded
