---


- name: Create a production machine
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  remote_user: root 
  vars_files:
    - env_vars/base.yml
    - env_vars/production.yml
  roles:
    - common
    - python
    - postgresql
    - apps


