---


- name: Set up a virtual machine via Vagrant
  hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  vars_files:
    - group_vars/all/vault.yml
    - group_vars/all/apps.yml
    - env_vars/base.yml
    - env_vars/vagrant.yml
  roles:
    - common
    - memcached
    - python
    - postgresql
    - fail2ban
    - s3cmd
    - apps
