---

# Note: Only https git repos will work. Don't use git@...

apps:
  - git_repo: 'https://github.com/philgyford/samuelpepys-twitter.git'
    git_directory: 'samuelpepys-twitter'
    virtualenv: 'samuelpepys-twitter'
  - virtualenv: gyford
  - repo: myphpapp

