---

# Note: Only https git repos will work. Don't use git@...

apps:
  - app_directory: 'samuelpepys-twitter'
    git_repo: 'https://github.com/philgyford/samuelpepys-twitter.git'
    git_repo_branch: 'master'
    pip_requirements_file: 'requirements.txt'
    virtualenv_name: 'samuelpepys-twitter'

  - app_directory: 'pepysdiary'
    django_settings_file: 'pepysdiary/settings/live.py'
    git_repo: 'https://github.com/philgyford/pepysdiary.git'
    git_repo_branch: 'master'
    pip_requirements_file: 'requirements.txt'
    virtualenv_name: 'pepysdiary'

  - app_directory: myphpapp
