---

# This will be populated in the roles/apps/set_python_versions.yml tasks.
# It will be like [ {'name': 'appname', 'python_version': '2.7.11'}, {...} ]
python_versions: []

# Note: Only https git repos will work. Don't use git@...
apps:
  - name: 'samuelpepys-twitter'
    git_repo: 'https://github.com/philgyford/samuelpepys-twitter.git'
    git_repo_branch: 'master'
    pip_requirements_file: 'requirements.txt'

  - name: 'pepysdiary'
    git_repo: 'https://github.com/philgyford/pepysdiary.git'
    git_repo_branch: 'ansible'
    pip_requirements_file: 'requirements.txt'
    db_type: 'postgresql'
    db_password: '{{ vault.pepysdiary.db_password }}'
    allowed_hosts:
      production: ['pepysdiary.com', 'www.pepysdiary.com']
      vagrant: ['pepysdiary.dev', 'www.pepysdiary.dev']
    django_settings_module:
      production: 'pepysdiary.settings.production'
      vagrant: 'pepysdiary.settings.vagrant'
    nginx_config: {}
    gunicorn_config:
      production:
        max_requests: 1000 # Restarts after this many requests.
        num_workers: 3 # Rule of thumb: 2 * CPUs + 1
      vagrant:
        max_requests: 1 # Reloads code on every request.
        num_workers: 3
      # Also, optional: timeout_seconds

  - name: myphpapp
