---

- name: Install python packages
  apt: name={{ item }} force=yes state=installed
  with_items:
    - python-dev
    - python-pip
    - python-pycurl
    - python-virtualenv

- include: virtualenvwrapper.yml

