---

- name: Install python packages
  apt: name={{ item }} force=yes state=installed
  with_items:
    - python-dev
    - python-pip
    - python-pycurl
    - python-virtualenv
  tags:
    - box
    - packages
    - python

- include: pyenv.yml
  tags:
    - box
    - python
    - pyenv
