---

- name: Install packages for pyenv installation
  apt: pkg={{ item }} state=present
  with_items:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
  tags: packages

- name: Install pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "{{ pyenv_path }}"
  tags: packages

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages

- name: Install pyenv-virtualenv plugin
  git:
    repo: https://github.com/yyuu/pyenv-virtualenv.git
    dest: "{{ pyenv_path }}/plugins/pyenv-virtualenv"
  tags: packages

- name: Add path etc to .bashrc.
  lineinfile:
    dest: "{{ deploy_user_rc_file }}"
    state: present
    create: yes
    line: "{{ item }}"
  with_items:
    - '# Added by Ansible for pyenv.'
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - 'export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'
    - 'eval "$(pyenv virtualenv-init -)"'
  tags: packages

- name: Ensure .pyenv permissions are set properly
  file: path={{ pyenv_path }}
        recurse=yes
        owner={{ ubuntu_deploy_user }}
        group={{ ubuntu_deploy_group }}
        state=directory

- name: Install a default python version
  become: yes
  become_user: '{{ ubuntu_deploy_user }}'
  shell: . {{ deploy_user_rc_file }} && {{ pyenv_path }}/libexec/pyenv install {{ default_python_version }}
    creates="{{ pyenv_path }}/versions/{{ default_python_version }}"

- name: Set default python version
  copy:
    content: '{{ default_python_version }}'
    dest: '{{ pyenv_path }}/version'
