---

env_name: 'base'

ubuntu_deploy_user: deploy
ubuntu_deploy_user_id: 5000
ubuntu_deploy_group: deploy
ubuntu_deploy_group_id: 5000

ubuntu_deploy_public_keys:
  - ~/.ssh/id_rsa.pub

ubuntu_ssh_port: 22

ubuntu_update_apt_cache: yes

# Deny access on all but a few ports:
ubuntu_use_firewall: yes

# Change the SSH port, disallow password authentication, disallow root login:
ubuntu_restrict_ssh: yes

# Deploy user's home directory:
deploy_user_home: '/home/{{ ubuntu_deploy_user }}'

# Where the code will live, eg `/home/deploy/webapps` will have the `pepysdiary` app's code at `/home/deploy/webapps/pepysdiary`:
apps_path: '{{ deploy_user_home }}/webapps'

# The .bashrc file that we'll use to update PATH etc:
deploy_user_rc_file: '{{ deploy_user_home }}/.bashrc'

# Where pyenv will be installed:
pyenv_path: '{{ deploy_user_home }}/.pyenv'

# Base version of python to be installed with pyenv:
# (Not entirely sure we need to do this, or should bother.)
default_python_version: '3.5.1'
