---

# Make crypted passwords:
#
# pip install passlib
# python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"

ubuntu_deploy_password: '$6$rounds=656000$onqTkZCRMWVbL2Wc$deRbKjDVYeIDSVOCJd1pG1E0sj5iHOzlb6Owx0j4qHBuA9UDFQc7XzBWLL6HKxO7K2awKf3P5z9FSMlgMxooM1'

ubuntu_deploy_user: deploy

ubuntu_deploy_public_keys:
  - ~/.ssh/id_rsa.pub

ubuntu_ssh_port: 22

ubuntu_update_apt_cache: yes

# Deny access on all but a few ports:
ubuntu_use_firewall: yes

# Change the SSH port, disallow password authentication, disallow root login:
ubuntu_restrict_ssh: yes

# Where the code will live, eg `/webapps` will have the `pepysdiary` app's
# code at `/webapps/pepysdiary`:
apps_path: '/webapps'

virtualenvwrapper_shell_rc_file: '/home/{{ ubuntu_deploy_user }}/.bashrc'
virtualenv_home_path: '/home/{{ ubuntu_deploy_user }}/.virtualenvs'


