---

# This would happen anyway when the git repo is checked out, but just in case
# an app doesn't have one, we still want to create a directory for it.
# Even if only for its .python_version file.

- name: Create directories for apps
  file:
    path: "{{ apps_path }}/{{ item.name }}"
    state: directory
    owner: "{{ ubuntu_deploy_user }}"
    group: "{{ ubuntu_deploy_group }}"
    mode: 0755
  with_items: active_apps
  # Probably not on Vagrant because we use synced_folders:
  when: create_app_directories

