---

- name: List active apps
  debug: msg="DOING TASKS FOR APPS - {{ active_apps|join(', ', attribute='name') }}."
  tags:
    - apps
    - cron
    - deploy
    - django
    - git
    - gunicorn
    - nginx
    - packages
    - postgresql
    - supervisor
    - virtualenvs

- include: install_app_packages.yml
  tags:
    - apps
    - deploy
    - packages

- include: create_app_directories.yml
  tags:
    - apps
    - deploy
    - virtualenvs

- include: set_up_git_repos.yml
  tags:
    - apps
    - deploy
    - git

- include: set_python_versions.yml
  tags:
    - apps
    - deploy

- include: set_up_virtualenvs.yml
  tags:
    - apps
    - deploy
    - virtualenvs

- include: set_up_postgresql.yml
  tags:
    - apps
    - postgresql

- include: set_up_django.yml
  tags:
    - apps
    - deploy
    - django

- include: set_up_gunicorn.yml
  tags:
    - apps
    - gunicorn

- include: set_up_supervisor.yml
  tags:
    - apps
    - gunicorn
    - supervisor

- include: set_up_nginx.yml
  tags:
    - apps
    - nginx

- include: set_up_cron.yml
  tags:
    - apps
    - cron
    - deploy

