---

# Include the encrypted variables.
# Need to give this the tags for all tasks in this role:
- include_vars: vars/vault.yml
  tags:
    - deploy
    - django
    - django.collectstatic
    - django.migrate
    - django.syncdb
    - git
    - gunicorn
    - nginx
    - postgresql
    - supervisor
    - testing
    - virtualenvs

- include: create_app_directories.yml
  tags:
    - deploy
    - virtualenvs

- include: set_up_git_repos.yml
  tags:
    - deploy
    - git

- include: set_python_versions.yml
  tags:
    - testing

- include: set_up_virtualenvs.yml
  tags:
    - deploy
    - virtualenvs

- include: set_up_postgresql.yml
  tags:
    - postgresql

- include: set_up_django.yml
  tags:
    - deploy
    - django

- include: set_up_gunicorn.yml
  tags:
    - gunicorn

- include: set_up_supervisor.yml
  tags:
    - supervisor

- include: set_up_nginx.yml
  tags:
    - nginx
