---

- include_vars: vars/vault.yml

- include: set_up_git_repos.yml
  tags:
    - deploy
    - git

- include: set_up_virtualenvs.yml
  tags:
    - deploy
    - virtualenvs

- include: set_up_postgresql.yml
  tags:
    - postgresql

#- include: set_up_django.yml
  # tags:
  #   - django
