---

- debug: msg="{{ vault.pepysdiary.akismet_api_key }}"
  tags: test

- include: create_app_directories.yml
  tags:
    - deploy
    - virtualenvs

- include: set_up_git_repos.yml
  tags:
    - deploy
    - git

- include: set_python_versions.yml
  tags:
    - testing

- include: set_up_virtualenvs.yml
  tags:
    - deploy
    - virtualenvs

- include: set_up_postgresql.yml
  tags:
    - postgresql

- include: set_up_django.yml
  tags:
    - deploy
    - django

- include: set_up_gunicorn.yml
  tags:
    - gunicorn

- include: set_up_supervisor.yml
  tags:
    - supervisor

- include: set_up_nginx.yml
  tags:
    - nginx
