---

- name: Run the Django syncdb command
  with_items: apps
  when: item.django_settings_file is defined and
        item.virtualenv_name is defined
  django_manage:
    command: syncdb
    app_path: "{{ app_path }}/{{ item.app_directory }}"
    virtualenv: "{{ virtualenv_home_path }}/{{ item.virtualenv_name }}"
    settings: "{{ item.django_settings_file }}"
  environment: django_environment
  when: run_django_syncdb is defined and run_django_syncdb
  tags: django.syncdb

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_collectstatic is defined and run_django_collectstatic
  tags:
    - django.collectstatic
    - deploy
