---

- name: Set up git repos for apps
  become: yes
  become_user: '{{ ubuntu_deploy_user }}'
  when: item.git_repo is defined
  with_items: apps
  git:
    repo: '{{ item.git_repo }}'
    version: "{{ item.git_repo_branch | default('master') }}"
    dest: "{{ apps_path }}/{{ item.name }}"
    accept_hostkey: yes

- name: Delete all .pyc files
  become: yes
  become_user: '{{ ubuntu_deploy_user }}'
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ apps_path }}"
