---

- name: Ensure supervisor service is started
  service: name=supervisor state=started enabled=yes

- name: Create Supervisor config file
  template: src=supervisor_config.j2
            dest=/etc/supervisor/conf.d/{{ item.name }}.conf
            backup=yes
  with_items: apps
  when: item.gunicorn_config is defined

- name: Re-read Supervisor config files
  supervisorctl: name={{ item.name }}_gunicorn state=present
  with_items: apps
  when: item.gunicorn_config is defined

- name: Restart Supervisor
  supervisorctl: name={{ item.name }}_gunicorn state=restarted
  with_items: apps
  when: item.gunicorn_config is defined
