---

- name: Set up git repos for apps
  become: yes
  become_user: '{{ ubuntu_deploy_user }}'
  git:
    repo: '{{ item.git_repo }}'
    version: "{{ item.git_repo_branch | default('master') }}"
    dest: "{{ apps_path }}/{{ item.name }}"
    accept_hostkey: yes
  with_items: active_apps
  # Probably not on vagrant, because we're using a local synced folder:
  when: item.git_repo is defined and check_out_git_repos

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ apps_path }}"
