---

- name: Install python versions for apps
  become: yes
  become_user: '{{ ubuntu_deploy_user }}'
  with_items: apps
  when: item.python_version is defined
  shell: . {{ deploy_user_rc_file }} && {{ pyenv_path }}/libexec/pyenv install {{ item.python_version }}
  args:
    creates: "{{ pyenv_path }}/versions/{{ item.python_version }}/bin/python"
  tags:
    - virtualenvs

- name: Create virtualenvs for apps
  become: yes
  become_user: '{{ ubuntu_deploy_user }}'
  with_items: apps
  when: item.python_version is defined
  shell: . {{ deploy_user_rc_file }} && {{ pyenv_path }}/libexec/pyenv virtualenv {{ item.python_version }} {{ item.name }}
  args:
    creates: "{{ pyenv_path }}/versions/{{ item.name }}/bin/activate"
  tags:
    - virtualenvs
