---

# As deploy user, because .pyenv is in its home directory.
- name: Install python versions for apps
  become: yes
  become_user: '{{ ubuntu_deploy_user }}'
  with_items: apps
  when: item.python_version is defined
  shell: . {{ deploy_user_rc_file }} && {{ pyenv_path }}/libexec/pyenv install {{ item.python_version }}
  args:
    creates: "{{ pyenv_path }}/versions/{{ item.python_version }}/bin/python"
  tags:
    - virtualenvs

# As deploy user, because .pyenv is in its home directory.
- name: Create virtualenvs for apps
  become: yes
  become_user: '{{ ubuntu_deploy_user }}'
  with_items: apps
  when: item.python_version is defined
  shell: . {{ deploy_user_rc_file }} && {{ pyenv_path }}/libexec/pyenv virtualenv {{ item.python_version }} {{ item.name }}
  args:
    creates: "{{ pyenv_path }}/versions/{{ item.name }}/bin/activate"
  tags:
    - virtualenvs

# Set the virtualenv name in each repo's .python-version file.
- name: Create .python-version files for virtualenvs
  with_items: apps
  when: item.python_version is defined
  copy:
    dest: "{{ apps_path }}/{{ item.name }}/.python-version"
    content: "{{ item.name }}"
  tags:
    - virtualenvs
