---


# Also in set_up_gunicorn.yml
- name: Create log folder, if it doesn't already exist
  with_items: apps
  when: item.nginx_config is defined
  file:
    path: '{{ pyenv_path }}/versions/{{ item.name }}/logs/'
    owner: '{{ ubuntu_deploy_user }}'
    group: '{{ ubuntu_deploy_group }}'
    mode: 0774
    state: directory

- name: Create Nginx configuration files for apps
  template: src=nginx_site_config_default.j2
            dest=/etc/nginx/sites-available/{{ item.name }}
            backup=yes
  with_items: apps
  when: item.nginx_config is defined
  notify: reload nginx
  tags:
    - deploy

- name: Ensure default Nginx site is disabled
  command: rm /etc/nginx/sites-enabled/default
           removes=/etc/nginx/sites-enabled/default
  notify: reload nginx

- name: Ensure apps' Ningx sites are enabled
  command: ln -s /etc/nginx/sites-available/{{ item.name }}
           /etc/nginx/sites-enabled/{{ item.name }}
           creates=/etc/nginx/sites-enabled/{{ item.name }}
  with_items: apps
  when: item.nginx_config is defined
  notify: reload nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes

- name: Create the maintenance page
  become: yes
  become_user: '{{ ubuntu_deploy_user }}'
  with_items: apps
  when: item.nginx_config is defined
  template:
    src: maintenance_off.html
    dest: '{{ pyenv_path }}/versions/{{ item.name }}/maintenance_off.html'
    mode: 0664
