---

# - name: Django - Run the syncdb command
#   become_user: postgres
#   with_items: apps
#   when: item.django_settings_file is defined
#   django_manage:
#     command: syncdb
#     app_path: '{{ apps_path }}/{{ item.name }}'
#     virtualenv: '{{ pyenv_path }}/versions/{{ item.name }}'
#     settings: '{{ item.django_settings_file }}'
#   environment: '{{ item.environment_variables }}'
#   # when: run_django_syncdb is defined and run_django_syncdb
#   tags:
#     - django.syncdb

- name: Django - Run database migrations
  become_user: postgres
  with_items: apps
  when: item.django_settings_file is defined
  django_manage:
    command: migrate
    app_path: '{{ apps_path }}/{{ item.name }}'
    virtualenv: '{{ pyenv_path }}/versions/{{ item.name }}'
    settings: '{{ item.django_settings_file }}'
  environment: '{{ item.environment_variables }}'
  # when: run_django_db_migrations is defined and run_django_db_migrations
  tags:
    - django.migrate

# - name: Django - Run collectstatic
#   django_manage:
#     command: collectstatic
#     app_path: "{{ project_path }}"
#     virtualenv: "{{ virtualenv_path }}"
#     settings: "{{ django_settings_file }}"
#   environment: django_environment
#   when: run_django_collectstatic is defined and run_django_collectstatic
#   tags:
#     - django.collectstatic
#     - deploy
