---

# - name: Django - Run the syncdb command
#   become_user: postgres
#   with_items: apps
#   when: item.django_settings_module is defined
#   django_manage:
#     command: syncdb
#     app_path: '{{ apps_path }}/{{ item.name }}'
#     virtualenv: '{{ pyenv_path }}/versions/{{ item.name }}'
#     settings: '{{ item.django_settings_module[env_name] }}'
#   tags:
#     - django.syncdb

- name: Django - Run database migrations
  become_user: postgres
  django_manage:
    command: migrate
    app_path: '{{ apps_path }}/{{ item.name }}'
    virtualenv: '{{ pyenv_path }}/versions/{{ item.name }}'
    settings: '{{ item.django_settings_module[env_name] }}'
  with_items: apps
  when: item.django_settings_module is defined
  environment:
    # Env vars aren't currently being picked up from virtualenv:
    SECRET_KEY: '{{ vault[item.name].django_secret_key }}'
    DB_NAME: '{{ item.name }}'
    DB_USERNAME: '{{ item.name }}'
    DB_HOST: 'localhost'
    DB_PASSWORD: '{{ vault[item.name].db_password }}'
  tags:
  - django.migrate

- name: Django - Run collectstatic
  django_manage:
    command: collectstatic
    app_path: '{{ apps_path }}/{{ item.name }}'
    virtualenv: '{{ pyenv_path }}/versions/{{ item.name }}'
    settings: '{{ item.django_settings_module[env_name] }}'
  with_items: apps
  when: item.django_settings_module is defined
  environment:
    # Env vars aren't currently being picked up from virtualenv:
    SECRET_KEY: '{{ vault[item.name].django_secret_key }}'
  tags:
    - django.collectstatic
