---

- name: Update APT package cache
  apt: update_cache={{ ubuntu_update_apt_cache }} cache_valid_time=3600
  tags:
    -- box
    -- packages

- name: Upgrade APT to the latest packages
  apt: upgrade=safe
  tags:
    -- box
    -- packages

- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags:
    -- box
    -- packages

- name: Install packages
  apt: name={{ item }} state=installed
  with_items:
    - build-essential
    - fail2ban
    - git
    - htop
    - libmemcached-dev
    - ntp
    - ufw
    - unattended-upgrades
    - vim
  tags:
    -- box
    -- packages

- name: Adjust APT update intervals
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic
  tags:
    -- box
    -- packages
