---

- name: Update APT package cache
  apt: update_cache={{ ubuntu_update_apt_cache }} cache_valid_time=3600

- name: Upgrade APT to the latest packages
  apt: upgrade=safe

- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc

- name: Install packages
  apt: name={{ item }} state=installed
  with_items:
    - build-essential
    - fail2ban
    - git
    - htop
    - libmemcached-dev
    - nginx
    - ntp
    - python-dev # So we can pip install setproctitle
    - supervisor
    - ufw
    - unattended-upgrades
    - vim

- name: Adjust APT update intervals
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic
