---

- include: create_swap_file.yml
- include: create_users.yml
- include: install_packages.yml

- include: set_up_firewall.yml
  when: ubuntu_use_firewall

- include: configure_ssh.yml
  when: ubuntu_restrict_ssh

- include: set_timezone.yml

